### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by sviter** [earwig/copyvios#25]
In [this request] (http://tools.wmflabs.org/copyvios/?lang=ru&project=wikipedia&title=%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9+%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9+%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87&oldid=&action=search&use_engine=1&use_links=1&turnitin=1)
I'v got an error:
`Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 104, in index
    query = do_check()
  File "./copyvios/checker.py", line 38, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 74, in _get_results
    query.turnitin_result = search_turnitin(query.title, query.lang)
  File "./copyvios/turnitin.py", line 22, in search_turnitin
    return TurnitinResult(_make_api_request(page_title, lang))
  File "./copyvios/turnitin.py", line 35, in _make_api_request
    parsed_api_result = literal_eval(result.text)
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    <body bgcolor="#f0f0f8">
    ^
SyntaxError: invalid syntax `

**Comment by earwig** [comment]
@fhocutt ?

**Comment by fhocutt** [comment]
Whoa, that's interesting. I'll take a look at it. At a first glance, looks like an issue with literal_eval.

**Comment by fhocutt** [comment]
Right: looks like it's causing a UnicodeDecodeError on the Plagiabot end, and instead of handling that internally or serving an error message, the server is providing an HTML page with stack trace details: 

http://tools.wmflabs.org/eranbot/plagiabot/api.py?action=suspected_diffs&page_title=%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B9%20%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87&report=1

I'll see about adding a check for that this week.

**Comment by earwig** [comment]
Ah-hah, so it's not technically our fault. A bit disappointing to see Unicode problems on their end, though...

**Comment by earwig** [comment]
Looks to be fixed upstream: valhallasw/plagiabot/issues/3
